def criar_gold_interrupcao_tratada(con):
    con.execute("DROP TABLE IF EXISTS gold_interrupcao_tratada")
    con.execute(
        """
        CREATE TABLE gold_interrupcao_tratada AS
        WITH raw_base AS (
            SELECT
                CAST(r.NUM_SEQ_INTRP_CHVP_HIADMS AS VARCHAR) AS PID_INTRP_CONJTO_PIN,
                CAST(r.PID_POSTO_PIN_PRIM_HIADMS AS VARCHAR) AS PID_POSTO_PIN,
                CAST(r.INDIC_AREA_REDE_POSTO_PIN_PRIM_HIADMS AS VARCHAR) AS INDIC_AREA_REDE_POSTO_PIN,
                CAST(r.NUM_ALIM_INTRP_PIN_PRIM_HIADMS AS VARCHAR) AS ALIM_INTRP_PIN,
                CAST(r.ESTADO_INTRP_ULT_HIADMS AS VARCHAR) AS ESTADO_INTRP_RAW,
                CAST(r.ALIM_INTRP_PRIM_HIADMS AS VARCHAR) AS ALIM_INTRP,
                CAST(r.CAR_SE_INTRP_PRIM_HIADMS AS VARCHAR) AS CAR_SE,
                CAST(r.INDIC_INTRP_SE_ALIM_INTRP_ULT_HIADMS AS VARCHAR) AS INDIC_INTRP_SE_ALIM,
                CAST(r.PID_OCOR_INTRP_ULT_HIADMS AS VARCHAR) AS NUM_OCORRENCIA_ADMS,
                CAST(r.INDIC_INTRP_AT_INTRP_ULT_HIADMS AS VARCHAR) AS INDIC_INTRP_AT,
                CAST(r.CONS_INTRP_PRIM_HIADMS AS VARCHAR) AS CONS_INTRP,
                REPLACE(CAST(r.KVA_INTRP_PRIM_HIADMS AS VARCHAR), '.', ',') AS KVA_INTRP,
                CAST(r.NUM_OPER_CHV_INTRP_ULT_HIADMS AS VARCHAR) AS NUM_OPER_CHV_INTRP,
                CAST(r.NUM_FUNCAO_ELET_INTRP_PRIM_HIADMS AS VARCHAR) AS NUM_FUNCAO_ELET_HCAI,
                CAST(r.NUM_FUNCAO_ELET_INTRP_PRIM_HIADMS AS VARCHAR) AS DESC_INTRP,
                CAST(r.INDIC_VALID_POS_OPER_INTRP_ULT_HIADMS AS VARCHAR) AS VALID_POS_OPERACAO,
                r.DATA_HORA_INIC_INTRP_ULT_HIADMS AS DATA_HORA_INIC_INTRP,
                r.DATA_HORA_FIM_INTRP_ULT_HIADMS AS DATA_HORA_FIM_INTRP,
                CAST(r.TIPO_EQP_INTRP_PRIM_HIADMS AS VARCHAR) AS TIPO_EQP_INTRP,
                CAST(r.COORD_X_INTRP_PRIM_HIADMS AS VARCHAR) AS COORD_X_INTRP,
                CAST(r.COORD_Y_INTRP_PRIM_HIADMS AS VARCHAR) AS COORD_Y_INTRP,
                CAST(r.NUM_SEQ_INTRP_CHVP_HIADMS AS VARCHAR) AS NUM_SEQ_INTRP,
                CAST(r.COD_CAUSA_INTRP_ULT_HIADMS AS VARCHAR) AS COD_CAUSA_INTRP,
                CAST(r.COD_COMP_INTRP_ULT_HIADMS AS VARCHAR) AS COD_COMP_INTRP,
                CAST(r.COD_AREA_ELET_INTRP_ULT_HIADMS AS VARCHAR) AS COD_AREA_ELET_INTRP,
                CAST(r.COD_GRUPO_COMP_INTRP_ULT_HIADMS AS VARCHAR) AS COD_GRUPO_COMP_INTRP,
                CAST(r.COD_COND_CLIMA_INTRP_ULT_HIADMS AS VARCHAR) AS COD_COND_CLIMA_INTRP,
                CAST(r.COD_TIPO_INTRP_ULT_HIADMS AS VARCHAR) AS COD_TIPO_INTRP,
                CAST(r.INDIC_JUMP_INTRP_ULT_HIADMS AS VARCHAR) AS INDIC_JUMP_INTRP,
                CAST(r.NUM_PROTOC_JUSTIF_RESP_INTRP_ULT_HIADMS AS VARCHAR) AS NUM_PROTOC_JUSTIF_RESP_INTRP,
                CAST(r.TIPO_PROTOC_JUSTIF_INTRP_ULT_HIADMS AS VARCHAR) AS TIPO_PROTOC_JUSTIF_INTRP,
                CAST(r.COD_CONJTO_ELET_ANEEL_INTRP_PRIM_HIADMS AS VARCHAR) AS COD_CONJTO_ELET_ANEEL_INTRP,
                CAST(r.INDIC_CALC_DMIC_INTRP_ULT_HIADMS AS VARCHAR) AS INDIC_CALC_DMIC_INTRP,
                CAST(r.INDIC_PONTO_CONEX_INTRP_PRIM_HIADMS AS VARCHAR) AS INDIC_PONTO_CONEX_INTRP,
                CAST(r.NUM_GEO_CHV_INTRP_PRIM_HIADMS AS VARCHAR) AS NUM_GEO_CHV_INTRP,
                CAST(r.TIPO_REDE_CHV_INTRP_PRIM_HIADMS AS VARCHAR) AS TIPO_REDE_CHV_INTRP,
                CAST(r.TIPO_CHV_INTRP_PRIM_HIADMS AS VARCHAR) AS TIPO_CHV_INTRP,
                CAST(r.INDIC_PROPR_POSTO_INTRP_PRIM_HIADMS AS VARCHAR) AS INDIC_PROPR_POSTO_INTRP,
                CAST(r.TENSAO_OPER_ALIM_INTRP_PRIM_HIADMS AS VARCHAR) AS TENSAO_OPER_ALIM_INTRP,
                CAST(r.INDIC_DESLIG_ENT_SERV_INTRP_ULT_HIADMS AS VARCHAR) AS INDIC_DESLIG_ENT_SERV_INTRP,
                CAST(r.INDIC_PROPR_CHVP_INTRP_PRIM_HIADMS AS VARCHAR) AS INDIC_PROPR_CHVP_INTRP,
                CAST(r.INDIC_CHVP_INIC_ALIM_INTRP_PRIM_HIADMS AS VARCHAR) AS INDIC_CHVP_INIC_ALIM_INTRP,
                CAST(r.NUM_SEQ_INTRP_CHVP_HIADMS AS VARCHAR) AS PID,
                CAST(r.NUM_SEQ_INTRP_CHVP_HIADMS AS VARCHAR) AS PID_INTRP_UCI,
                CAST(r.NUM_SEQ_INTRP_CHVP_HIADMS AS VARCHAR) AS NUM_INTRP_UCI,
                CAST(r.PID_POSTO_PIN_PRIM_HIADMS AS VARCHAR) AS NUM_POSTO_UCI,
                CAST(r.NUM_UC_UCI_CHVP_HIADMS AS VARCHAR) AS NUM_UC_UCI,
                CAST(r.TIPO_SIT_UC_UCI_PRIM_HIADMS AS VARCHAR) AS TIPO_SIT_UC_UCI,
                r.DATA_HORA_INIC_INTRP_ULT_HIADMS AS DTHR_INICIO_INTRP_UC_RAW,
                CAST(r.NUM_INTRP_INIC_MANOBRA_UCI_ULT_HIADMS AS VARCHAR) AS NUM_INTRP_INIC_MANOBRA_UCI_RAW,
                CAST(r.NUM_MOTIVO_TRAT_DIF_UCI_ULT_HIADMS AS VARCHAR) AS NUM_MOTIVO_TRAT_DIF_UCI_RAW,
                CAST(r.INDIC_UC_ACESS_UCI_PRIM_HIADMS AS VARCHAR) AS UC_ACESSANTE,
                CAST(r.SIGLA_REGIONAL_INTRP_PRIM_HIADMS AS VARCHAR) AS SIGLA_REGIONAL,
                CAST(r.NUM_PROTOC_JUSTIF_RESP_UCI_ULT_HIADMS AS VARCHAR) AS NUM_PROTOC_JUSTIF_RESP_UCI,
                CAST(r.TIPO_PROTOC_JUSTIF_UCI_ULT_HIADMS AS VARCHAR) AS TIPO_PROTOC_JUSTIF_UCI,
                CAST(r.PID_PIN_PRIM_HIADMS AS VARCHAR) AS PID_PIN,
                CAST(r.INDIC_PROCES_IND_PIN_ULT_HIADMS AS VARCHAR) AS INDIC_PROCES_IND_PIN,
                CAST(r.INDIC_SIT_PROCES_INDIC_UCI_ULT_HIADMS AS VARCHAR) AS INDIC_SIT_PROCES_INDIC_UCI_RAW
            FROM raw_db.hiadms_raw r
            WHERE r.DATA_HORA_INIC_INTRP_ULT_HIADMS IS NOT NULL
              AND r.DATA_HORA_FIM_INTRP_ULT_HIADMS IS NOT NULL
              AND r.DATA_HORA_FIM_INTRP_ULT_HIADMS >= r.DATA_HORA_INIC_INTRP_ULT_HIADMS
              AND NULLIF(TRIM(CAST(r.COD_CAUSA_INTRP_ULT_HIADMS AS VARCHAR)), '') IS NOT NULL
              AND NULLIF(TRIM(CAST(r.COD_COMP_INTRP_ULT_HIADMS AS VARCHAR)), '') IS NOT NULL
        ),
        tratado AS (
            SELECT
                b.*,
                t.ESTADO_INTRP AS ESTADO_INTRP_TRAT,
                t.NUM_MOTIVO_TRAT_DIF_UCI AS NUM_MOTIVO_TRAT_DIF_UCI_TRAT,
                t.INDIC_SIT_PROCES_INDIC_UCI AS INDIC_SIT_PROCES_INDIC_UCI_TRAT,
                t.DTHR_INICIO_INTRP_UC_AJUSTADO AS DTHR_INICIO_INTRP_UC_TRAT,
                t.NUM_INTRP_INIC_MANOBRA_UCI AS NUM_INTRP_INIC_MANOBRA_UCI_TRAT,
                t.ACAO_AJUSTE_PARCIAL,
                t.ACAO_REDIREC_MANOBRA_ESTADO_7
            FROM raw_base b
            LEFT JOIN adms_iqs_alterados t
              ON COALESCE(TRIM(CAST(t.NUM_OCORRENCIA_ADMS AS VARCHAR)), '') = COALESCE(TRIM(CAST(b.NUM_OCORRENCIA_ADMS AS VARCHAR)), '')
             AND COALESCE(TRIM(CAST(t.NUM_SEQ_INTRP AS VARCHAR)), '') = COALESCE(TRIM(CAST(b.NUM_SEQ_INTRP AS VARCHAR)), '')
             AND COALESCE(TRIM(CAST(t.NUM_UC_UCI AS VARCHAR)), '') = COALESCE(TRIM(CAST(b.NUM_UC_UCI AS VARCHAR)), '')
             AND COALESCE(TRIM(CAST(t.NUM_POSTO_UCI AS VARCHAR)), '') = COALESCE(TRIM(CAST(b.NUM_POSTO_UCI AS VARCHAR)), '')
        )
        SELECT DISTINCT
            PID_INTRP_CONJTO_PIN,
            PID_POSTO_PIN,
            INDIC_AREA_REDE_POSTO_PIN,
            ALIM_INTRP_PIN,
            COALESCE(ESTADO_INTRP_TRAT, ESTADO_INTRP_RAW) AS ESTADO_INTRP,
            ALIM_INTRP,
            CAR_SE,
            INDIC_INTRP_SE_ALIM,
            NUM_OCORRENCIA_ADMS,
            INDIC_INTRP_AT,
            CONS_INTRP,
            KVA_INTRP,
            NUM_OPER_CHV_INTRP,
            NUM_FUNCAO_ELET_HCAI,
            DESC_INTRP,
            VALID_POS_OPERACAO,
            DATA_HORA_INIC_INTRP,
            DATA_HORA_FIM_INTRP,
            TIPO_EQP_INTRP,
            COORD_X_INTRP,
            COORD_Y_INTRP,
            NUM_SEQ_INTRP,
            COD_CAUSA_INTRP,
            COD_COMP_INTRP,
            COD_AREA_ELET_INTRP,
            COD_GRUPO_COMP_INTRP,
            COD_COND_CLIMA_INTRP,
            COD_TIPO_INTRP,
            INDIC_JUMP_INTRP,
            NUM_PROTOC_JUSTIF_RESP_INTRP,
            TIPO_PROTOC_JUSTIF_INTRP,
            COD_CONJTO_ELET_ANEEL_INTRP,
            INDIC_CALC_DMIC_INTRP,
            INDIC_PONTO_CONEX_INTRP,
            NUM_GEO_CHV_INTRP,
            TIPO_REDE_CHV_INTRP,
            TIPO_CHV_INTRP,
            INDIC_PROPR_POSTO_INTRP,
            TENSAO_OPER_ALIM_INTRP,
            INDIC_DESLIG_ENT_SERV_INTRP,
            INDIC_PROPR_CHVP_INTRP,
            INDIC_CHVP_INIC_ALIM_INTRP,
            PID,
            PID_INTRP_UCI,
            NUM_INTRP_UCI,
            NUM_POSTO_UCI,
            NUM_UC_UCI,
            TIPO_SIT_UC_UCI,
            CASE
                WHEN ACAO_AJUSTE_PARCIAL IS NOT NULL THEN DTHR_INICIO_INTRP_UC_TRAT
                ELSE DTHR_INICIO_INTRP_UC_RAW
            END AS DTHR_INICIO_INTRP_UC,
            CASE
                WHEN ACAO_AJUSTE_PARCIAL IS NOT NULL
                  OR ACAO_REDIREC_MANOBRA_ESTADO_7 IS NOT NULL
                THEN NUM_INTRP_INIC_MANOBRA_UCI_TRAT
                ELSE NUM_INTRP_INIC_MANOBRA_UCI_RAW
            END AS NUM_INTRP_INIC_MANOBRA_UCI,
            COALESCE(NUM_MOTIVO_TRAT_DIF_UCI_TRAT, NUM_MOTIVO_TRAT_DIF_UCI_RAW) AS NUM_MOTIVO_TRAT_DIF_UCI,
            UC_ACESSANTE,
            SIGLA_REGIONAL,
            NUM_PROTOC_JUSTIF_RESP_UCI,
            TIPO_PROTOC_JUSTIF_UCI,
            PID_PIN,
            INDIC_PROCES_IND_PIN,
            COALESCE(INDIC_SIT_PROCES_INDIC_UCI_TRAT, INDIC_SIT_PROCES_INDIC_UCI_RAW) AS INDIC_SIT_PROCES_INDIC_UCI
        FROM tratado
        WHERE TRIM(CAST(COALESCE(ESTADO_INTRP_TRAT, ESTADO_INTRP_RAW) AS VARCHAR)) = '4'
        """
    )
    con.execute(
        """
        CREATE OR REPLACE TABLE silver_interrupcao_tratada AS
        SELECT *
        FROM gold_interrupcao_tratada
        """
    )
