SELECT
    TO_CHAR(hcai.DATA_INTRP_HCAI, 'YYYYMM') AS ano_mes,
    hcai.TIPO_PROTOC_JUSTIF_HCAI AS TIPO_PROTOCOLO,
    COUNT(*) AS Quantidade_registros_banco,
    COUNT(DISTINCT hcai.NUM_UC_HCAI) AS qtd_UC_afetadas,
    COUNT(hcai.NUM_MOTIVO_TRAT_DIF_HCAI) AS registros_expurgados,
    COUNT(hcai.NUM_INTRP_INIC_MANOBRA_HCAI) AS registros_inicio_manobra
FROM iqs.HIST_CONS_AFETADO_INTERRUPCAO hcai 
WHERE TO_CHAR(hcai.DATA_INTRP_HCAI, 'YYYYMM') = '202605' 
GROUP BY TO_CHAR(hcai.DATA_INTRP_HCAI, 'YYYYMM'),  hcai.TIPO_PROTOC_JUSTIF_HCAI
ORDER BY  hcai.TIPO_PROTOC_JUSTIF_HCAI;