/*
Parâmetros:

    num_uc      - Número da unidade consumidora
    data_inicio - mês ano inicial, formato 'YYYYMM'
    data_fim    - mês ano final, formato 'YYYYMM'
*/

SELECT
    TO_CHAR(DATA_INTRP_HCAI, 'YYYYMM') AS ANOMES,
    HCAI.NUM_UC_HCAI,

    /* DIC LIQ */
    SUM(
        CASE
            WHEN SUBSTR(NVL(D.SIGLA_TIQS_DIC, 'DIC_'), 1, 4) = 'DIC_'
             AND D.SIGLA_REID_DIC IS NULL
            THEN (I.DATA_HORA_FIM_INTRP - I.DATA_HORA_INIC_INTRP) * 24
            ELSE 0
        END
    ) AS DIC_LIQ,

    /* DIC BRUTO */
    SUM(
        CASE
            WHEN SUBSTR(NVL(D.SIGLA_TIQS_DIC, 'DIC_'), 1, 4) = 'DIC_'
             AND NVL(TRIM(D.SIGLA_REID_DIC), 'X') NOT IN
                 ('DFC', 'USU', 'USI', 'ACI', 'FM', 'ERR', 'DUP', 'CHP', 'DFI', 'PTP')
            THEN (I.DATA_HORA_FIM_INTRP - I.DATA_HORA_INIC_INTRP) * 24
            ELSE 0
        END
    ) AS DIC_BRT,

    /* FIC LIQ */
    COUNT(
        CASE
            WHEN SUBSTR(NVL(F.SIGLA_TIQS_FIC, 'FIC_'), 1, 4) = 'FIC_'
             AND F.SIGLA_REID_FIC IS NULL
            THEN NUM_INTRP_HCAI
        END
    ) AS FIC_LIQ,

    /* FIC BRT */
    COUNT(
        CASE
            WHEN SUBSTR(NVL(F.SIGLA_TIQS_FIC, 'FIC_'), 1, 4) = 'FIC_'
             AND NVL(TRIM(F.SIGLA_REID_FIC), 'X') NOT IN
                 ('DFC', 'USU', 'USI', 'ACI', 'FM', 'ERR', 'DUP', 'CHP', 'DFI', 'PTP', 'MAN')
            THEN NUM_INTRP_HCAI
        END
    ) AS FIC_BRT

FROM HIST_CONS_AFETADO_INTERRUPCAO HCAI
JOIN INTERRUPCAO I
  ON HCAI.NUM_INTRP_HCAI = I.NUM_SEQ_INTRP

LEFT JOIN (
    SELECT
        MD.NUM_HIST_CONS_AFET_MECA,
        TD.SIGLA_TIQS AS SIGLA_TIQS_DIC,
        RD.SIGLA_REID AS SIGLA_REID_DIC
    FROM MOTIVO_EXCL_CONS_AFETADO_INTRP MD
    LEFT JOIN TIPO_INDICADOR_QUALID_SERV_DIS TD
      ON NVL(MD.NUM_TIPO_INDIC_MECA, 0) = TD.NUM_SEQ_TIQS
    LEFT JOIN REGRA_EXPURGO_INDIC_DISTR RD
      ON NVL(MD.NUM_REGRA_MECA, 0) = RD.NUM_SEQ_REID
    WHERE SUBSTR(TD.SIGLA_TIQS, 1, 4) = 'DIC_'
) D
  ON HCAI.NUM_SEQ_HCAI = D.NUM_HIST_CONS_AFET_MECA

LEFT JOIN (
    SELECT
        MD.NUM_HIST_CONS_AFET_MECA,
        TD.SIGLA_TIQS AS SIGLA_TIQS_FIC,
        RD.SIGLA_REID AS SIGLA_REID_FIC
    FROM MOTIVO_EXCL_CONS_AFETADO_INTRP MD
    LEFT JOIN TIPO_INDICADOR_QUALID_SERV_DIS TD
      ON NVL(MD.NUM_TIPO_INDIC_MECA, 0) = TD.NUM_SEQ_TIQS
    LEFT JOIN REGRA_EXPURGO_INDIC_DISTR RD
      ON NVL(MD.NUM_REGRA_MECA, 0) = RD.NUM_SEQ_REID
    WHERE SUBSTR(TD.SIGLA_TIQS, 1, 4) = 'FIC_'
) F
  ON HCAI.NUM_SEQ_HCAI = F.NUM_HIST_CONS_AFET_MECA

WHERE HCAI.NUM_UC_HCAI IN (:num_uc)
  AND HCAI.DATA_INTRP_HCAI >= TO_DATE(:data_inicio, 'YYYYMM')
  AND HCAI.DATA_INTRP_HCAI < ADD_MONTHS(TO_DATE(:data_fim, 'YYYYMM'), 1)

GROUP BY
    TO_CHAR(DATA_INTRP_HCAI, 'YYYYMM'),
    HCAI.NUM_UC_HCAI

ORDER BY ANOMES
