SELECT
    ue.ISN_UC,
    ue.NUM_CONJTO_ANEEL_FIXO_UC AS cea,
    ue.INDIC_LOCAL_TEC_UC AS urb_rur,
    ue.COD_GRUPO_NIVEL_TENSAO_UC,
    ue.COD_NIVEL_TENSAO_UC,
    NVL(ue.VAL_BASE_CALC_COMPEN_UC, 0) AS VRC
FROM CIS.UC_ENERGIA ue
WHERE ue.TIPO_SIT_UC IN ('LG', 'CR')
