SELECT
    CASE
        WHEN GROUPING(rd.SIGLA_RDIS) = 1 THEN 'COPEL'
        ELSE rd.SIGLA_RDIS
    END AS REGIONAL_TOTAL,
    CASE rd.SIGLA_RDIS
        WHEN 'CSL' THEN 'P'
        WHEN 'NRT' THEN 'L'
        WHEN 'NRO' THEN 'M'
        WHEN 'LES' THEN 'C'
        WHEN 'OES' THEN 'V'
        ELSE 'COPEL'
    END AS SIGLA_REGIONAL,
    CASE rd.SIGLA_RDIS
        WHEN 'CSL' THEN 'SODPGO'
        WHEN 'NRT' THEN 'SODLNA'
        WHEN 'NRO' THEN 'SODMGA'
        WHEN 'LES' THEN 'SODCTA'
        WHEN 'OES' THEN 'SDOCEL'
        ELSE 'COPEL'
    END AS SIGLA_SEVIDOR,
    TO_CHAR(ANO_MES_HQCL, 'yyyy-mm') AS ANOMES,
    SUM(QTDE_CONS_FAT_URB_HQCL + QTDE_CONS_FAT_RUR_HQCL) AS UC_FATURADA
FROM iqs.HIST_QTDE_CONS_LOCAL hqcl
INNER JOIN cis.LOCALIDADE l
    ON l.COD_LOCAL = hqcl.COD_LOCAL_HQCL
LEFT JOIN cis.SECCIONAL_DISTRIBUICAO sc
    ON l.COD_SECCION_DISTR_LOCAL = sc.COD_SDIS
LEFT JOIN cis.REGIONAL_DISTRIBUICAO rd
    ON sc.COD_REG_DISTR_SDIS = rd.COD_RDIS
WHERE ANO_MES_HQCL = TO_DATE(:anomes, 'yyyy-mm')
  AND rd.SIGLA_RDIS <> 'SCD'
GROUP BY
    ROLLUP(rd.SIGLA_RDIS),
    TO_CHAR(ANO_MES_HQCL, 'yyyy-mm')
ORDER BY
    ANOMES DESC,
    REGIONAL_TOTAL ASC
