/*
Simulacao ISE por UC.

Regra:
- CHI/DIC bruto verifica se houve potencial ISE.
- CHI/DIC liquido mede quanto pode ser reclassificado.
- COD_CAUSA_INTRP = 52 e elegivel para ISE.
- COD_COMP_INTRP = 52 continua sendo regra separada de compensacao/ressarcimento.
*/

WITH base AS (
    SELECT
        NULLIF(TRIM(CAST(NUM_UC_UCI AS VARCHAR)), '') AS UC,
        NULLIF(TRIM(CAST(NUM_OCORRENCIA_ADMS AS VARCHAR)), '') AS NUM_OCORRENCIA_ADMS,
        NULLIF(TRIM(CAST(NUM_SEQ_INTRP AS VARCHAR)), '') AS NUM_SEQ_INTRP,
        NULLIF(TRIM(CAST(COD_CAUSA_INTRP AS VARCHAR)), '') AS COD_CAUSA_INTRP,
        COALESCE(TRY_CAST(DURACAO_HORA AS DOUBLE), 0) AS DURACAO_HORA,
        CASE
            WHEN NULLIF(TRIM(CAST(COD_CAUSA_INTRP AS VARCHAR)), '') IN (
                '2', '4', '5', '6', '7', '8', '9', '13', '15', '23', '24', '28',
                '39', '40', '41', '52', '54', '69', '82'
            )
            THEN 'S'
            ELSE 'N'
        END AS ISE_CAUSA_ELEGIVEL,
        COALESCE(NULLIF(TRIM(CAST(SIGLA_TIQS_DIC AS VARCHAR)), ''), 'DIC_') AS SIGLA_TIQS_DIC_REF,
        NULLIF(TRIM(CAST(SIGLA_REID_DIC AS VARCHAR)), '') AS SIGLA_REID_DIC_REF,
        COALESCE(NULLIF(TRIM(CAST(SIGLA_TIQS_FIC AS VARCHAR)), ''), 'FIC_') AS SIGLA_TIQS_FIC_REF,
        NULLIF(TRIM(CAST(SIGLA_REID_FIC AS VARCHAR)), '') AS SIGLA_REID_FIC_REF
    FROM gold_apuracao_uc
    WHERE NULLIF(TRIM(CAST(NUM_UC_UCI AS VARCHAR)), '') IS NOT NULL
),
marcada AS (
    SELECT
        *,
        CASE
            WHEN ISE_CAUSA_ELEGIVEL = 'S'
             AND SUBSTR(SIGLA_TIQS_DIC_REF, 1, 4) = 'DIC_'
             AND COALESCE(SIGLA_REID_DIC_REF, 'X') NOT IN
                 ('DFC','USU','USI','ACI','FM','ERR','DUP','CHP','DFI','PTP')
            THEN DURACAO_HORA
            ELSE 0
        END AS ISE_CHI_BRUTO_REFERENCIA,
        CASE
            WHEN ISE_CAUSA_ELEGIVEL = 'S'
             AND SUBSTR(SIGLA_TIQS_DIC_REF, 1, 4) = 'DIC_'
             AND SIGLA_REID_DIC_REF IS NULL
            THEN DURACAO_HORA
            ELSE 0
        END AS ISE_CHI_LIQUIDO_RECLASSIFICAVEL,
        CASE
            WHEN ISE_CAUSA_ELEGIVEL = 'S'
             AND SUBSTR(SIGLA_TIQS_FIC_REF, 1, 4) = 'FIC_'
             AND COALESCE(SIGLA_REID_FIC_REF, 'X') NOT IN
                 ('DFC','USU','USI','ACI','FM','ERR','DUP','CHP','DFI','PTP','MAN')
            THEN 1
            ELSE 0
        END AS ISE_CI_BRUTO_REFERENCIA,
        CASE
            WHEN ISE_CAUSA_ELEGIVEL = 'S'
             AND SUBSTR(SIGLA_TIQS_FIC_REF, 1, 4) = 'FIC_'
             AND SIGLA_REID_FIC_REF IS NULL
            THEN 1
            ELSE 0
        END AS ISE_CI_LIQUIDO_RECLASSIFICAVEL
    FROM base
)
SELECT
    UC,
    CASE
        WHEN SUM(ISE_CHI_BRUTO_REFERENCIA) > 0
          OR SUM(ISE_CI_BRUTO_REFERENCIA) > 0
        THEN 'S'
        ELSE 'N'
    END AS ISE_POTENCIAL,
    CASE
        WHEN SUM(ISE_CHI_LIQUIDO_RECLASSIFICAVEL) > 0
          OR SUM(ISE_CI_LIQUIDO_RECLASSIFICAVEL) > 0
        THEN 'S'
        ELSE 'N'
    END AS ISE_RECLASSIFICAVEL,
    COUNT(*) AS EVENTOS_AVALIADOS,
    SUM(CASE WHEN ISE_CAUSA_ELEGIVEL = 'S' THEN 1 ELSE 0 END) AS EVENTOS_CAUSA_ISE,
    COUNT(DISTINCT CASE WHEN ISE_CAUSA_ELEGIVEL = 'S' THEN NUM_OCORRENCIA_ADMS END) AS OCORRENCIAS_CAUSA_ISE,
    SUM(ISE_CI_BRUTO_REFERENCIA) AS ISE_CI_BRUTO_REFERENCIA,
    SUM(ISE_CI_LIQUIDO_RECLASSIFICAVEL) AS ISE_CI_LIQUIDO_RECLASSIFICAVEL,
    SUM(ISE_CHI_BRUTO_REFERENCIA) AS ISE_CHI_BRUTO_REFERENCIA,
    SUM(ISE_CHI_LIQUIDO_RECLASSIFICAVEL) AS ISE_CHI_LIQUIDO_RECLASSIFICAVEL,
    MAX(ISE_CHI_BRUTO_REFERENCIA) AS ISE_DMIC_BRUTO_REFERENCIA,
    MAX(ISE_CHI_LIQUIDO_RECLASSIFICAVEL) AS ISE_DMIC_LIQUIDO_RECLASSIFICAVEL,
    STRING_AGG(DISTINCT COD_CAUSA_INTRP, ', ' ORDER BY COD_CAUSA_INTRP) FILTER (
        WHERE ISE_CAUSA_ELEGIVEL = 'S'
    ) AS COD_CAUSAS_ISE
FROM marcada
GROUP BY UC;
